CREATE DATABASE TIMESHEET;

GRANT ALL PRIVILEGES ON TIMESHEET.* TO TIMESHEET@localhost IDENTIFIED BY 'TIMESHEET' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TIMESHEET.* TO TIMESHEET@"%" IDENTIFIED BY 'TIMESHEET' WITH GRANT OPTION;

DROP TABLE TIMESHEET.CUSTOMER;
DROP TABLE TIMESHEET.TIMESHEETS;

CREATE TABLE TIMESHEET.CUSTOMER
(
	CUSTOMER_ID INTEGER NOT NULL, 
	USER_NAME VARCHAR(30) NOT NULL, 
	PASSWORD VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL, 
	LAST_NAME VARCHAR(30) NOT NULL,
	AUTHORITY VARCHAR(12) NOT NULL,
	PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE TIMESHEET.TIMESHEETS
(
	TIMESHEET_ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL, 
	WEEKNO INTEGER NOT NULL,
	PROJECT VARCHAR(30) NOT NULL, 
	WP INTEGER NOT NULL, 
	TOTAL DECIMAL(6,2), 
	SAT DECIMAL(6,2), 
	SUN DECIMAL(6,2), 
	MON DECIMAL(6,2), 
	TUE DECIMAL(6,2), 
	WED DECIMAL(6,2), 
	THU DECIMAL(6,2), 
	FRI DECIMAL(6,2), 
	NOTE VARCHAR(30) NOT NULL
);

INSERT INTO TIMESHEET.CUSTOMER VALUES( '001','super','super','Bruce','Link','Superuser' );
INSERT INTO TIMESHEET.CUSTOMER VALUES( '002','user1','user1','Huanan','Wang','user' );
INSERT INTO TIMESHEET.CUSTOMER VALUES( '003','user2','user2','Fred','Xie','user' );
INSERT INTO TIMESHEET.CUSTOMER VALUES( '004','user3','user3','Jin','An','user' );
INSERT INTO TIMESHEET.CUSTOMER VALUES( '331','user4','user4','Bloggs','Loe','user' );

INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','132','AA123','4.0','','','','4','','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','132','AB112','2.0','','','','2','','','','Requested by Tracy' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','132','AA221','8.0','','','8.0','','','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','1205','12110','0.0','','','','','','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','13000','13000','3.5','','','','','3.5','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','12450','12450','10.0','','','','2.0','3.0','3.0','2.0','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','32000','32000','9.0','','','','','5.0','','4.0','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '1','331','52','45010','45010','9.0','','','','','','','4.0','5.0' );